# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c29b45cd00f4e922c0c74776af088d9bd859a2e208ddf5c49ab011ca76a877185acaf19ccecbbfb0bd9f041dd2c57c5322017e7e3ce5e6efa538b8001396ac1

test:
  secret_key_base: 5313331cffe0bbfd480e34513861fd20cd0d409abe9a582c761423c657d3b17c89c1fa6f8a961812672eeb531a208a6b5e5b6156e19a85b45593c2c6d8d1d05f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
